#!/usr/bin/env lua

local ltui        = require("ltui")
local application = ltui.application
local event       = ltui.event
local rect        = ltui.rect
local window      = ltui.window
local demo        = application()
local dialog_input = ltui.inputdialog:new("dialog.input", rect {0, 0, 50, 8})


function demo:init()
    application.init(self, "demo")
    self:background_set("blue")

-- Blank screen with blue background

end

demo:run()
